### PR TITLE
Umbrella

### PR DESCRIPTION
**Pull request by aniemeyer**
A new method
SimplicialSurfaceByUmbrellaDescriptor
and a function
UmbrellaDescriptorOfSurface

### CODE REVIEW

**Comment by aniemeyer** [comment]
I have included some additional test files, to increase code coverage

**Comment by aniemeyer** [comment]
I do not understand why the build fails. It seems to have something to do with the AttributeScheduler

**Comment by aniemeyer** [comment]
test_example_threeTrianglesOnEdge.g 
the first surface cannot be built

**Review by markusbaumeister — APPROVED** [review]
This looks good.

**Pull request merged**
