### PR TITLE
Examples for cut and mend

### PR DESCRIPTION
**Pull request by MeikeWeiss**

### CODE REVIEW

**Review by markusbaumeister — CHANGES_REQUESTED** [review]
Good content.

I can think of only one improvement: you newly created the images for "butterfly" and "disjointTriangles". Since both appear several times, it would make sense to extract the code into a separate image file (then any change only needs to apply in one place). All of these custom image files lie in the doc/ -folder and start with "Image_". 
Consider doc/Image_EyeStone.tex for an example of a complete tikz-picture and doc/Image_OpenBag.tex for an example of an incomplete tikz-picture.

**Comment by MeikeWeiss** [comment]
I am sorry, I did a mistake. The last commit shouldn't be in this pull request. It should be in a new one. But in the commit I did the issues #78, #52, #49, #47. I hope that it is not a big problem.

**Comment by markusbaumeister** [comment]
Unfortunately, the last commit seems to have introduced a merge conflict. Thus, it would be preferable if you could split it into a separate pull request, so the remainder can be accepted. This link should explain the necessary procedure:
https://gist.github.com/loilo/930f141d9acf89e9e734ffa042acd750

Concerning the changes in the last commit, there seems to be a slight misunderstanding concerning the method names: Adding a NC (short for "no check") to the name indicates that no tests are performed, to allow higher efficiency. Thus, the "normal" method usually performs some checks before calling the "NC"-version that does the actual work.

**Comment by MeikeWeiss** [comment]
Thanks for your help! I think this pull request is now correct.

**Review by markusbaumeister — APPROVED** [review]

**Pull request merged**
