### PR TITLE
Move old files into deprecated-directory

### PR DESCRIPTION
**Pull request by markusbaumeister**
The package still contains some very old code (the first version of the package, containing the general folding formalism from my master thesis). After a significant rewrite, I never found the time to reintroduce that formalism. To avoid clutter, the code is now moved into a separate directory.

### CODE REVIEW

**Review by MeikeWeiss — DISMISSED** [review]
Looks good and creates a better overview!

**Comment by MeikeWeiss** [comment]
There are some merge conflicts, can you resolve them?

**Review by MeikeWeiss — APPROVED** [review]
Thanks!

**Review by TomGoertzen — APPROVED** [review]
Looks good for me!

**Pull request merged**
